// Generated by Wrangler on Thu Apr 25 2024 09:18:25 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
}
